### PR TITLE
Fire completion block failures instead of returning silently

### LINKED ISSUE #25: Methods return early instead of failing with an error
Essentially, the fix that was applied in #22 on the `login(username:password:completion:)` method should be applied to all `else` blocks after the response is returned.

### PR DESCRIPTION
**Pull request by AngeloStavrow**
This PR closes #25.

### CODE REVIEW

File: Sources/WriteFreely/WFClient.swift [hunk 1]
```diff
@@ -57,10 +57,16 @@ public class WFClient {
         alias: String? = nil,
         completion: @escaping (Result<WFCollection, Error>) -> Void
     ) {
-        if token == nil && user == nil { return }
-        guard let tokenToVerify = token ?? user?.token else { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: Do we still need to `return` here, or is that handled further down in the logic?

Comment (AngeloStavrow) [reply Sources/WriteFreely/WFClient.swift]: Whoops! Good catch — fixed in 1213eef.

Comment (thebaer) [reply Sources/WriteFreely/WFClient.swift]: :+1: There are also a few other spots where the `return` was dropped. I'll mark those, in case they still need to be there.

File: Sources/WriteFreely/WFClient.swift [hunk 2]
```diff
@@ -367,10 +406,16 @@ public class WFClient {
         from collectionAlias: String,
         completion: @escaping (Result<Bool, Error>) -> Void
     ) {
-        if token == nil && user == nil { return }
-        guard let tokenToVerify = token ?? user?.token else { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: `return` was dropped here.

File: Sources/WriteFreely/WFClient.swift [hunk 3]
```diff
@@ -415,8 +460,11 @@ public class WFClient {
         in collectionAlias: String? = nil,
         completion: @escaping (Result<WFPost, Error>) -> Void
     ) {
-        if token == nil && user == nil { return }
-        guard let tokenToVerify = token ?? user?.token else { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: `return` was dropped here.

File: Sources/WriteFreely/WFClient.swift [hunk 4]
```diff
@@ -482,10 +533,16 @@ public class WFClient {
         byId postId: String,
         completion: @escaping (Result<WFPost, Error>) -> Void
     ) {
-        if token == nil && user == nil { return }
-        guard let tokenToVerify = token ?? user?.token else { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: `return` was dropped here.

File: Sources/WriteFreely/WFClient.swift [hunk 5]
```diff
@@ -524,10 +581,14 @@ public class WFClient {
         from collectionAlias: String,
         completion: @escaping (Result<WFPost, Error>) -> Void
     ) {
-        if token == nil && user == nil { return }
-        guard let tokenToVerify = token ?? user?.token else { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: `return` was dropped here.

File: Sources/WriteFreely/WFClient.swift [hunk 6]
```diff
@@ -569,10 +630,16 @@ public class WFClient {
         with modifyToken: String? = nil,
         completion: @escaping (Result<WFPost, Error>) -> Void
     ) {
-        if token == nil && user == nil { return }
-        guard let tokenToVerify = token ?? user?.token else { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: `return` was dropped here.

File: Sources/WriteFreely/WFClient.swift [hunk 7]
```diff
@@ -624,10 +691,16 @@ public class WFClient {
         with modifyToken: String? = nil,
         completion: @escaping (Result<Bool, Error>) -> Void
     ) {
-        if token == nil && user == nil { return }
-        guard let tokenToVerify = token ?? user?.token else { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: `return` was dropped here.

File: Sources/WriteFreely/WFClient.swift [hunk 8]
```diff
@@ -705,11 +781,17 @@ public class WFClient {
     ///   - token: The token to invalidate.
     ///   - completion: A handler for the `Bool` object returned on success, or `Error` on failure.
     public func logout(token: String? = nil, completion: @escaping (Result<Bool, Error>) -> Void) {
-        if token == nil && user == nil { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: `return` was dropped here.

File: Sources/WriteFreely/WFClient.swift [hunk 9]
```diff
@@ -733,11 +815,17 @@ public class WFClient {
     ///   - token: The access token for the user to fetch.
     ///   - completion: A handler for the `Data` object returned on success, or `Error` on failure.
     public func getUserData(token: String? = nil, completion: @escaping (Result<Data, Error>) -> Void) {
-        if token == nil && user == nil { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: `return` was dropped here.

File: Sources/WriteFreely/WFClient.swift [hunk 10]
```diff
@@ -759,11 +847,17 @@ public class WFClient {
     ///   - token: The access token for the user whose collections are to be retrieved.
     ///   - completion: A handler for the `[WFCollection]` object returned on success, or `Error` on failure.
     public func getUserCollections(token: String? = nil, completion: @escaping (Result<[WFCollection], Error>) -> Void) {
-        if token == nil && user == nil { return }
+        if token == nil && user == nil { completion(.failure(WFError.couldNotComplete)) }
```
Comment (thebaer) [inline Sources/WriteFreely/WFClient.swift]: `return` was dropped here.

**Comment by AngeloStavrow** [comment]
@thebaer Thanks for noting these!

**Comment by thebaer** [comment]
No problem -- looks good!

**Review by thebaer — APPROVED** [review]
